local settings	= require("defrend.render.settings").spot_light
local uniforms	= require("defrend.render.uniforms").spot_light
local queue		= require("defrend.scripts.configurators.queue")
local msgs		= require("defrend.messages")

go.property("enabled", true)
go.property("light_start", 0)

go.property("range_attenuation_power", 1)
go.property("spread_attenuation_power", 1)
go.property("shadow_bias_near", 0.1)
go.property("shadow_bias_far", 0.6)
go.property("pcf_samples", 8)
go.property("poisson_samples", 4)
go.property("poisson_scale", 5)
go.property("hash_factor", 7879)
go.property("hash_scale", 5)
go.property("soft_penumbras", true)

local function do_init(self)
	settings.enabled = self.enabled

	settings.range_attenuation = self.range_attenuation_power
	settings.spread_attenuation = self.spread_attenuation_power
	settings.shadow_bias_near = self.shadow_bias_near
	settings.shadow_bias_far = self.shadow_bias_far
	settings.pcf_samples = self.pcf_samples
	settings.poisson_samples = self.poisson_samples
	settings.poisson_scale = self.poisson_scale
	settings.hash_factor = self.hash_factor
	settings.hash_scale = self.hash_scale
	settings.soft_penumbras = self.soft_penumbras

	uniforms.init()
end

function init(self)
	do_init(self)
	queue.init_pending_spot_lights()
end

function on_message(self, message_id, message, sender)
	if message_id == msgs.REFRESH then
		do_init(self)
	end
end

function on_reload(self)
	do_init(self)
end

function final(self)
	-- Add finalization code here
	-- Learn more: https://defold.com/manuals/script/
	-- Remove this function if not needed
end
