local settings	= require("defrend.render.settings")
local shadows	= require("defrend.render.shadows.point_light")

local MSG_ENABLE	= hash("enable")
local MSG_DISABLE	= hash("disable")
local MSG_REFRESH	= hash("refresh")
local MSG_UNIFORMS	= hash("uniforms")
local MTX_NAMES		= { "mtx_nx", "mtx_px", "mtx_ny", "mtx_py", "mtx_nz", "mtx_pz" }

go.property("enabled", true)

local function do_uniforms(self)
	self.params1.z = settings.point_light.shadow_bias_near
	self.params1.w = settings.point_light.shadow_bias_far
	go.set(self.model, "params1", self.params1)
end

local function do_init(self)
	self.url = msg.url(".")
	self.model = msg.url("#model")
	self.index = shadows.add_light(self.url)

	self.params1 = vmath.vector4()
	self.params1.x = settings.point_light.shadow_map_resolution
	self.params1.y = (self.index - 1) * settings.point_light.shadow_map_resolution

	do_uniforms(self)
end

function init(self)
	do_init(self)
end

function late_update(self)
	if not self.enabled then
		return
	end
	local views, proj = shadows.generate_matrices(self.url)
	if not (views and proj) then
		msg.post(self.url, MSG_DISABLE)
		return
	end
	for i = 1, #views do
		go.set(self.model, MTX_NAMES[i], proj * views[i])
	end
end

function on_reload(self)
	shadows.remove_light(self.url)
	do_init(self)
end

function final(self)
	shadows.remove_light(self.url)
end

-- update uniforms on minor changes; init everything when shadowmap changes
function on_message(self, message_id, message, sender)
	if message_id == MSG_ENABLE and not self.enabled then
		self.enabled = true
		self.index = shadows.add_light(self.url)
	elseif message_id == MSG_DISABLE and self.enabled then
		self.enabled = false
		shadows.remove_light(self.url)
	elseif message_id == MSG_REFRESH then
		shadows.remove_light(self.url)
		do_init(self)
	elseif message_id == MSG_UNIFORMS then
		do_uniforms(self)
	end
end
