local settings	= require("defrend.render.settings")
local shadows	= require("defrend.render.shadows.point_light")
local queue		= require("defrend.scripts.configurators.queue")
local msgs		= require("defrend.messages")

go.property("enabled", true)

local function do_uniforms(self)
	self.params1.z = settings.point_light.shadow_bias_near
	self.params1.w = settings.point_light.shadow_bias_far
	go.set(self.model, "params1", self.params1)
end

local function do_init(self)
	self.index = shadows.add_light(self.url)

	self.params1 = vmath.vector4()
	self.params1.x = settings.point_light.shadow_caster_count
	self.params1.y = (self.index - 1) * (1 / settings.point_light.shadow_caster_count) -- normalized y-offset in atlas

	self.mtx_lights = {}
	do_uniforms(self)
end

function init(self)
	self.url = msg.url(".")
	self.model = msg.url("#model")

	queue.add_pending_point_light(function ()
		do_init(self)
	end)
end

function late_update(self)
	if not self.enabled then
		return
	end
	local views, proj = shadows.generate_matrices(self.url)
	if not (views and proj) then
		msg.post(self.url, msgs.DISABLE)
		return
	end
	for i = 1, #views do
		self.mtx_lights[i] = proj * views[i]
	end
	go.set(self.model, "mtx_lights", self.mtx_lights)
end

function on_reload(self)
	shadows.remove_light(self.url)
	do_init(self)
end

function final(self)
	shadows.remove_light(self.url)
end

-- update uniforms on minor changes; init everything when shadowmap changes
function on_message(self, message_id, message, sender)
	if message_id == msgs.ENABLE and not self.enabled then
		self.enabled = true
		self.index = shadows.add_light(self.url)
	elseif message_id == msgs.DISABLE and self.enabled then
		self.enabled = false
		shadows.remove_light(self.url)
	elseif message_id == msgs.REFRESH then
		do_init(self)
	elseif message_id == msgs.UNIFORMS then
		do_uniforms(self)
	end
end
