local settings	= require("defrend.render.settings")
local shadows	= require("defrend.render.shadows.point_light")

local MSG_ENABLE	= hash("enable")
local MSG_DISABLE	= hash("disable")
local MSG_REFRESH	= hash("refresh")
local MTX_NAMES		= { "mtx_nx", "mtx_px", "mtx_ny", "mtx_py", "mtx_nz", "mtx_pz" }

go.property("enabled", true)

local function do_init(self)
	self.url = msg.url(".")
	self.model = msg.url("#model")
	self.index = shadows.add_light()
	self.params = vmath.vector4()
	self.params.x = settings.point_light_shadow.map_resolution
	self.params.y = (self.index - 1) * settings.point_light_shadow.map_resolution
	self.params.z = self.index
	self.params.w = settings.point_light_shadow.bias
end

function init(self)
	do_init(self)
end

function late_update(self)
	if not self.enabled then
		return
	end
	local views, proj = shadows.generate_matrices(self.url, self.index)
	if not (views and proj) then
		msg.post(self.url, MSG_DISABLE)
		return
	end
	go.set(self.model, "params", self.params)
	for i = 1, #views do
		go.set(self.model, MTX_NAMES[i], proj * views[i])
	end
end

function final(self)
	shadows.remove_light(self.index)
end

function on_message(self, message_id, message, sender)
	if message_id == MSG_ENABLE and not self.enabled then
		self.enabled = true
		self.index = shadows.add_light()
	elseif message_id == MSG_DISABLE and self.enabled then
		self.enabled = false
		shadows.remove_light(self.index)
	elseif message_id == MSG_REFRESH then
		do_init(self)
	end
end
