local settings	= require("defrend.render.settings").spot_light
local queue		= require("defrend.scripts.configurators.queue")
local msgs		= require("defrend.messages")

go.property("enabled", true)
go.property("light_start", 0)

-- set numeric properties to negative values to use the global defaults
go.property("range_attenuation_power", 1)
go.property("spread_attenuation_power", 1)
go.property("shadow_map", resource.render_target())
go.property("shadow_bias_near", 0.1)
go.property("shadow_bias_far", 0.6)
go.property("pcf_samples", 8)
go.property("poisson_samples", 4)
go.property("poisson_scale", 5)
go.property("hash_factor", 7879)
go.property("hash_scale", 5)
go.property("soft_penumbras", true)

local function property_or_default(property, default)
	if property < 0 then
		return property
	else
		return default
	end
end

local function do_init(self)
	self.start_attn = vmath.vector4()
	self.start_attn.x = self.light_start
	self.start_attn.y = property_or_default(self.range_attenuation_power, settings.range_attenuation)
	self.start_attn.z = property_or_default(self.spread_attenuation_power, settings.spread_attenuation)

	self.shadow_params1 = vmath.vector4()
	self.shadow_params1.x = property_or_default(self.shadow_bias_near, settings.shadow_bias_near)
	self.shadow_params1.y = property_or_default(self.shadow_bias_far, settings.shadow_bias_far)
	self.shadow_params1.z = property_or_default(self.soft_penumbras, settings.soft_penumbras)
	self.shadow_params1.w = property_or_default(self.pcf_samples, settings.pcf_samples)

	self.shadow_params2 = vmath.vector4()
	self.shadow_params2.x = property_or_default(self.poisson_samples, settings.poisson_samples)
	self.shadow_params2.y = property_or_default(self.poisson_scale, settings.poisson_scale)
	self.shadow_params2.z = property_or_default(self.hash_factor, settings.hash_factor)
	self.shadow_params2.w = property_or_default(self.hash_scale, settings.hash_scale)

	go.set(self.model, "start_attn", self.start_attn)
	go.set(self.model, "shadow_params1", self.shadow_params1)
	go.set(self.model, "shadow_params2", self.shadow_params2)
end

function init(self)
	self.url = msg.url(".")
	self.model = msg.url("#model")

	queue.add_pending_spot_light(function ()
		do_init(self)
	end)
end

function final(self)
	-- Add finalization code here
	-- Learn more: https://defold.com/manuals/script/
	-- Remove this function if not needed
end

function update(self, dt)
	-- Add update code here
	-- Learn more: https://defold.com/manuals/script/
	-- Remove this function if not needed
end

function late_update(self, dt)
	-- This function is called at the end of update cycle but before render
	-- Learn more: https://defold.com/manuals/script/
	-- Remove this function if not needed
end

function fixed_update(self, dt)
	if not self.enabled then
		return
	end
	-- This function is called if 'Fixed Update Frequency' is enabled in the Engine section of game.project
	-- Can be coupled with fixed updates of the physics simulation if 'Use Fixed Timestep' is enabled in
	-- Physics section of game.project
	-- Add update code here
	-- Learn more: https://defold.com/manuals/script/
	-- Remove this function if not needed
end

function on_message(self, message_id, message, sender)
	if message_id == msgs.ENABLE and not self.enabled then
		self.enabled = true
	elseif message_id == msgs.DISABLE and self.enabled then
		self.enabled = false
	elseif message_id == msgs.REFRESH then
		do_init(self)
	end
end

function on_input(self, action_id, action)
	-- Add input-handling code here. The game object this script is attached to
	-- must have acquired input focus:
	--
	--    msg.post(".", "acquire_input_focus")
	--
	-- All mapped input bindings will be received. Mouse and touch input will
	-- be received regardless of where on the screen it happened.
	-- Learn more: https://defold.com/manuals/input/
	-- Remove this function if not needed
end

function on_reload(self)
	-- Add reload-handling code here
	-- Learn more: https://defold.com/manuals/hot-reload/
	-- Remove this function if not needed
end
