local settings = require "defrend.render.settings"
local uniforms = require "defrend.render.uniforms"

go.property("enabled", false)

local function do_init(self)
	settings.gaussian_blur.enabled = self.enabled
	uniforms.gaussian_blur.init()
end

function init(self)
	do_init(self)
end

local MSG_REFRESH = hash("refresh")
function on_message(self, message_id, message, sender)
	if message_id == MSG_REFRESH then
		do_init(self)
	end
end
