components {
  id: "rotate"
  component: "/example/main/rotate.script"
}
embedded_components {
  id: "model"
  type: "model"
  data: "mesh: \"/builtins/assets/meshes/cube.dae\"\n"
  "name: \"{{NAME}}\"\n"
  "materials {\n"
  "  name: \"default\"\n"
  "  material: \"/defrend/materials/geometry/decal/decal.material\"\n"
  "  textures {\n"
  "    sampler: \"diffuse_map\"\n"
  "    texture: \"/example/assets/images/broken-ice-base.png\"\n"
  "  }\n"
  "  textures {\n"
  "    sampler: \"normal_map\"\n"
  "    texture: \"/example/assets/images/broken-ice-normal.png\"\n"
  "  }\n"
  "  textures {\n"
  "    sampler: \"spec_glow_map\"\n"
  "    texture: \"/example/assets/images/broken-ice-spec-glow.png\"\n"
  "  }\n"
  "}\n"
  ""
}
