embedded_components {
  id: "model"
  type: "model"
  data: "mesh: \"/builtins/assets/meshes/sphere.dae\"\n"
  "name: \"{{NAME}}\"\n"
  "materials {\n"
  "  name: \"default\"\n"
  "  material: \"/defrend/materials/geometry/light_volume/point_light_fixed.material\"\n"
  "  attributes {\n"
  "    name: \"color\"\n"
  "    double_values {\n"
  "      v: 0.0\n"
  "      v: 1.0\n"
  "      v: 0.0\n"
  "      v: 1.0\n"
  "    }\n"
  "  }\n"
  "  attributes {\n"
  "    name: \"radii\"\n"
  "    double_values {\n"
  "      v: 6.0\n"
  "      v: 8.0\n"
  "      v: 0.0\n"
  "      v: 0.0\n"
  "    }\n"
  "  }\n"
  "}\n"
  ""
}
