embedded_components {
  id: "model"
  type: "model"
  data: "mesh: \"/defrend/assets/lights/meshes/cone.glb\"\n"
  "name: \"{{NAME}}\"\n"
  "materials {\n"
  "  name: \"default\"\n"
  "  material: \"/defrend/materials/geometry/model/model.material\"\n"
  "  textures {\n"
  "    sampler: \"spec_glow_map\"\n"
  "    texture: \"/defrend/assets/textures/white.png\"\n"
  "  }\n"
  "  textures {\n"
  "    sampler: \"normal_map\"\n"
  "    texture: \"/defrend/assets/textures/flat.png\"\n"
  "  }\n"
  "  textures {\n"
  "    sampler: \"albedo_map\"\n"
  "    texture: \"/example/assets/images/red.png\"\n"
  "  }\n"
  "}\n"
  "create_go_bones: false\n"
  ""
}
