local M = {
	resolution_x = 0,
	resolution_y = 0,
	geometry = {
		models_enabled = true,
		sprites_enabled = true,
		billboards_enabled = true,
		decals_enabled = true,
		skybox_enabled = true,
	},
	light = {
		sunlight_enabled = true,
		point_lights_enabled = true,
		spot_lights_enabled = true,
		point_light_attenuation = 5,
		spot_light_range_attenuation = 5,
		spot_light_spread_attenuation = 1,
		fog_near = 800,
		fog_far = 1001,
		fog_color = vmath.vector4(0),
		ambient_color = vmath.vector4(0.75, 0.75, 0.75, 1.0),
		directional_color = vmath.vector4(1.0),
		directional_to = vmath.vector4(-1, -1, -1, 1),
	},
	shadow = {
		enabled = true,
		stable = true,
		pcf_samples = 8,
		poisson_samples = 4,
		poisson_scale = 3000,
		soft_penumbras = true,
		cascade = { 0.20, 0.10, 0.10, 0.20 },
		biases = { 0.5, 0.75, 0.75, 1.2 },
		transition_range = 10,
		z_padding_factor = 0.5,
		atlas_resolution = 4096,
		-- the rest will be calculated from camera settings combined with the preceding
		map_resolution = 1,
		map_dimension = 1,
		texel_size = 1,
		partitions = {},
		projections = {},
	},
	ssao = {
		enabled = true,
		downsample = false,
		blur = true,
		scale = 1.0,
		samples = 16,
		intensity = 1.5,
		bias_angle = 0.1,
		bias_dist = 0.5,
		min_distance = 1.0,
		max_distance = 4.0,
		attenuation = 1.0,
		radius = 2.0,
	},
	outline = {
		enabled = false,
		outline_color = vmath.vector4(0, 0, 0, 0.5),
		-- outline
		depth_threshold		= 0.025,
		normal_threshold	= 0.5,
		normal_smoothing	= 0.25,
		-- thickness
		min_thickness	= 0.5,
		max_thickness	= 1.3,
		min_distance	= 2.0,
		max_distance	= 75.0,
		-- grazing prevention
		grazing_fresnel_power			= 5.0,
		grazing_angle_mask_power		= 1.0,
		grazing_angle_modulation_factor	= 50.0,
	},
	glow = {
		enabled = true,
		downsample = true;
		separation = 1.0,
	},
	bloom = {
		enabled = false,
		threshold = 0.9,
		radius = 1,
		separation = 2,
		strength = 0.5,
	},
	box_blur = {
		radius = 1,
		separation = 1.0,
	},
	gaussian_blur = {
		enabled = false,
		downsample = true,
		separation = 1.0,
	},
	dual_kawase_blur = {
		enabled = false,
		iterations = 1,
		separation = 1.0,
		bloom = 1.0,
	},
	kuwahara_blur = {
		enabled = false,
		samples = 1,
	},
	dilate = {
		enabled = false,
		min_threshold = 0.1,
		max_threshold = 0.3,
		radius = 1,
		separation = 1,
	},
	dof = {
		enabled = false,
		focal_depth = 200,
		blur_start = 30,
		blur_full = 40,
	},
	gamma = {
		enabled = false,
		gamma = 2.2,
	},
	fxaa = {
		enabled = true,
		iterations = 3,
	},
	visualize = {
		option = nil,
	},
}

return M
