local visualize_panel	= require("defrend.gui.panels.visualization")
local cameras_panel		= require("defrend.gui.panels.cameras")
local geometry_panel	= require("defrend.gui.panels.geometry")
local lighting_panel	= require("defrend.gui.panels.lighting")
local shadows_panel		= require("defrend.gui.panels.shadows")
local ssao_panel		= require("defrend.gui.panels.ssao")
local glow_panel		= require("defrend.gui.panels.glow")
local dof_panel			= require("defrend.gui.panels.dof")
local outline_panel		= require("defrend.gui.panels.outline")
local kuwahara_panel	= require("defrend.gui.panels.kuwahara")
local bloom_panel		= require("defrend.gui.panels.bloom")
local dilate_panel		= require("defrend.gui.panels.dilate")
local gaussian_panel	= require("defrend.gui.panels.gaussian")
local kawase_panel		= require("defrend.gui.panels.dual_kawase")
local gamma_panel		= require("defrend.gui.panels.gamma")
local fxaa_panel		= require("defrend.gui.panels.fxaa")

local post_processors	= require("defrend.render.post_processors")

local outline			= require("defrend.render.post_processors.outline")
local gamma				= require("defrend.render.post_processors.gamma")
local glow				= require("defrend.render.post_processors.glow")
local bloom				= require("defrend.render.post_processors.bloom")
local kuwahara_blur		= require("defrend.render.post_processors.kuwahara_blur")
local gaussian_blur		= require("defrend.render.post_processors.gaussian_blur")
local dual_kawase_blur	= require("defrend.render.post_processors.dual_kawase_blur")
local dof				= require("defrend.render.post_processors.dof")
local fxaa				= require("defrend.render.post_processors.fxaa")

go.property("enabled", true)

local rendering = {
	{ name = "Cameras",		draw = cameras_panel },
	{ name = "Geometry",	draw = geometry_panel },
	{ name = "Lighting",	draw = lighting_panel },
	{ name = "Shadows",		draw = shadows_panel },
	{ name = "SSAO",		draw = ssao_panel },
}

local post_processing_panels = {
	[outline]			= { name = "Outline",			draw = outline_panel },
	[gamma]				= { name = "Gamma correction",	draw = gamma_panel },
	[glow]				= { name = "Glow",				draw = glow_panel },
	[bloom]				= { name = "Bloom",				draw = bloom_panel },
	[kuwahara_blur]		= { name = "Kuwahara blur",		draw = kuwahara_panel },
	[gaussian_blur]		= { name = "Gaussian blur",		draw = gaussian_panel },
	[dual_kawase_blur]	= { name = "Dual Kawase blur",	draw = kawase_panel },
	[dof]				= { name = "Depth of field",	draw = dof_panel },
	[fxaa]				= { name = "FXAA",				draw = fxaa_panel },
}
local ordered_list_copy = {}

local frames = 0
local elapsed = 0
local avg_fps = 0
local fps_history = {}
local max_history = 120

function init(self)
	imgui.set_ini_filename()

	for _ = 1, max_history do
		table.insert(fps_history, 0)
	end
	for _, v in ipairs(post_processors.ordered_list) do
		table.insert(ordered_list_copy, v)
	end
	timer.delay(1, true, function()
		if elapsed == 0 then
			avg_fps = 0
		else
			-- avg_fps = math.floor(frames / elapsed + 0.5)
			avg_fps = frames / elapsed
		end
		frames = 0
		elapsed = 0
		-- table.remove(fps_history, 1)
		-- table.insert(fps_history, avg_fps)
	end)
end

local vec3_zero = vmath.vector3()
function update(self, dt)
	if not self.enabled then
		return
	end

	imgui.set_next_window_pos(10, 10, imgui.COND_FIRSTUSEEVER)

	imgui.begin_window("Settings", false, imgui.WINDOWFLAGS_ALWAYSAUTORESIZE)

	elapsed = elapsed + dt
	frames = frames + 1
	imgui.text(("FPS: %.2f"):format(avg_fps))
	-- imgui.plot_lines("FPS plot", 0, 445, 50, fps_history)

	if imgui.tree_node("Visualizations") then
		visualize_panel(self)
		imgui.tree_pop()
	end

	imgui.separator()

	for _, panel in ipairs(rendering) do
		if imgui.tree_node(panel.name) then
			panel.draw(self)
			imgui.tree_pop()
		end
	end

	imgui.separator()

	local reordered = false
	for i, pp in ipairs(ordered_list_copy) do
		local panel = post_processing_panels[pp]
		local opened = imgui.tree_node(panel.name)

		imgui.push_style_var(imgui.STYLEVAR_FRAMEPADDING, vec3_zero)
		-- imgui.same_line(480)
		imgui.same_line(160)
		if imgui.button_arrow(panel.name .. " Up", imgui.DIR_UP) then
			post_processors.move_up(i)
			reordered = true
		end
		-- imgui.same_line(500)
		imgui.same_line(180)
		if imgui.button_arrow(panel.name .. " Down", imgui.DIR_DOWN) then
			post_processors.move_down(i)
			reordered = true
		end
		imgui.pop_style_var()

		if opened then
			panel.draw(self)
			imgui.tree_pop()
		end
	end

	imgui.end_window()

	if reordered then
		ordered_list_copy = {}
		for _, pp in ipairs(post_processors.ordered_list) do
			table.insert(ordered_list_copy, pp)
		end
		post_processors.regenerate_active_list()
		reordered = false
	end
end

function on_message(self, message_id, message, sender)
	if message_id == "enable" then
		self.enabled = true
	elseif message_id == "disable" then
		self.enabled = false
	end
end
